# VALITO LANDING #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbv-landing-deployment
  namespace: tiendas-rhino-4
  labels:
    app: tbv-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbv-landing
  template:
    metadata:
      labels:
        app: tbv-landing
    spec:
      containers:
        - name: harlem-landing
          image: southamerica-east1-docker.pkg.dev/diesel-talon-387022/landing-rhino/landing-rhino:tbv
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80